### ISSUE TITLE
Support comments

### ISSUE THREAD

**Issue by sbliven** [SacBase/sac-jupyter#4]
Adding a comment after the last statement in a cell will cause the next expression cell to throw an error.

Example:
```
a = 1; // Comment
```
```
a
```

Debugging with `%print` makes it clear what is happening. The easiest fix is probably to just append a newline after the statement list before the `Stdio::print` call.

**Comment by ashinkarov** [comment]
This is indeed a bug, and the suggested fix should be easy to implement.

**Comment by sbliven** [comment]
The workaround is to use inline comments `/* */` which work fine.
